// sfu-web/src/app/participant/participant.component.ts
import { Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-participant',
  templateUrl: './participant.component.html',
  styleUrls: ['./participant.component.scss']
})
export class ParticipantComponent implements OnInit {
  @ViewChild('player', { static: true })
  public player?: ElementRef<HTMLVideoElement>;

  @Input()
  public track?: MediaStreamTrack;

  ngOnInit(): void {
    if (this.track == null) return;
    if (this.player == null) return;
    this.player.nativeElement.srcObject = new MediaStream([this.track]);
  }
}

<video class="video" #player playsinline autoplay></video>

// sfu-web/src/components/Participant.tsx
import "./Participant.css";

interface ParticipantProps {
  track: MediaStreamTrack | null,
  mirrored: boolean,
}

function Participant(props: ParticipantProps) {
  if (props.track === null) {
    return <div className="track placeholder">
      No device selected
    </div>;
  }
  const track = props.track;
  const ref = (video: HTMLVideoElement | null) => {
    if (video === null) return;
    video.srcObject = new MediaStream([track]);
  };
  const mirrored = props.mirrored ? " mirrored" : "";
  return <video className={"track" + mirrored} playsInline autoPlay ref={ref}></video>;
}

export default Participant;
